# Generated by Django 5.2.3 on 2025-08-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('license_no', models.CharField(default='', max_length=15)),
                ('seat_capacity', models.IntegerField(default=30)),
                ('bus_type', models.CharField(default='Standard', max_length=10)),
                ('del_flag', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.operator')),
            ],
            options={
                'verbose_name_plural': 'List of Buses',
            },
        ),
    ]
