# Generated by Django 5.2.3 on 2025-08-06 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=5)),
                ('seat_status', models.CharField(default='Available', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'seat_no')},
            },
        ),
    ]
