# Generated by Django 5.2.3 on 2025-08-06 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_seat_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('seat_numbers', models.CharField(max_length=100)),
                ('booked_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='seat_status',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
    ]
