# Generated by Django 5.2.3 on 2025-08-06 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_delete_book_delete_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('total_seat', models.IntegerField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=6)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
            ],
        ),
    ]
