# Generated by Django 5.2.3 on 2025-08-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total_seat',
            field=models.IntegerField(),
        ),
    ]
