# Generated by Django 5.2.3 on 2025-08-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_ticket_total_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('KP', 'KPay'), ('WP', 'WavePay')], max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.ticket')),
            ],
        ),
    ]
