# Generated by Django 5.2.3 on 2025-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_feedback_options_feedback_overall_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_assigned',
            field=models.IntegerField(default=0),
        ),
    ]
