# Generated by Django 5.2.3 on 2025-09-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_bus_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
    ]
